#!/usr/bin/env node

const fs = require('fs');
const os = require('os');
const path = require('path');

function readStdin() {
  return new Promise((resolve) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
  });
}

function parseMessage(input) {
  try {
    return JSON.parse(String(input || '').split('\n').find(Boolean) || '{}');
  } catch {
    return {};
  }
}

(async function main() {
  const args = process.argv.slice(2);
  const sessionIndex = args.indexOf('--session');
  const sessionId = sessionIndex >= 0 && args[sessionIndex + 1]
    ? args[sessionIndex + 1]
    : `mock-kimi-${Date.now()}`;
  const isPlan = args.includes('--plan');

  const payload = parseMessage(await readStdin());
  const content = payload?.content;
  const parts = Array.isArray(content)
    ? content
    : (typeof content === 'string' && content.trim() ? [{ type: 'text', text: content.trim() }] : []);
  const promptText = parts
    .filter((part) => part?.type === 'text')
    .map((part) => part.text || '')
    .join(' ')
    .trim();
  const imageCount = parts.filter((part) => part?.type === 'image_url').length;

  const statePath = path.join(os.tmpdir(), `cc-web-mock-kimi-${sessionId}.json`);
  let state = {};
  try {
    state = JSON.parse(fs.readFileSync(statePath, 'utf8'));
  } catch {}

  if (promptText === '/compact') {
    state.compacted = true;
    fs.writeFileSync(statePath, JSON.stringify(state));
  }

  const isInitPrompt = promptText.includes('You are running cc-web\'s /init for a Kimi session.');
  if (isInitPrompt) {
    fs.writeFileSync(path.join(process.cwd(), 'AGENTS.md'), '# AGENTS.md\n\nGenerated by mock Kimi /init.\n');
  }

  if (promptText === 'trigger kimi context limit' && !state.compacted) {
    process.stderr.write('Context limit reached. Please use /compact and retry.\n');
    process.exit(1);
  }

  if (promptText && promptText !== '/compact' && !isInitPrompt) {
    process.stdout.write(`${JSON.stringify({
      role: 'assistant',
      content: '',
      tool_calls: [
        {
          id: 'kimi_tool_pwd',
          type: 'function',
          function: {
            name: 'shell_command',
            arguments: JSON.stringify({ command: 'pwd' }),
          },
        },
      ],
    })}\n`);
    process.stdout.write(`${JSON.stringify({
      role: 'tool',
      tool_call_id: 'kimi_tool_pwd',
      content: `pwd => /tmp/mock-kimi (${imageCount} image)`,
    })}\n`);
  }

  const responseText = promptText === '/compact'
    ? 'Kimi compact finished.'
    : isInitPrompt
      ? 'Kimi init finished.'
      : `Kimi mock handled (${imageCount} image, ${isPlan ? 'plan' : 'normal'}): ${promptText || '[no text]'}`;

  process.stdout.write(`${JSON.stringify({
    role: 'assistant',
    content: responseText,
  })}\n`);

  if (promptText === 'trigger kimi context limit' && state.compacted) {
    try { fs.unlinkSync(statePath); } catch {}
  }
})();
